export const SolarTerms = {
    'jq.dongZhi': 'Đông Chí',
    'jq.xiaoHan': 'Tiểu Hàn',
    'jq.daHan': 'Đại Hàn',
    'jq.liChun': 'Lập Xuân',
    'jq.yuShui': 'Vũ Thủy',
    'jq.jingZhe': 'Kinh Trập',
    'jq.chunFen': 'Xuân Phân',
    'jq.qingMing': 'Thanh Minh',
    'jq.guYu': 'Cốc Vũ',
    'jq.liXia': 'Lập Hạ',
    'jq.xiaoMan': 'Tiểu Mãn',
    'jq.mangZhong': 'Mang Chủng',
    'jq.xiaZhi': 'Hạ Chí',
    'jq.xiaoShu': 'Tiểu Thử',
    'jq.daShu': 'Đại Thử',
    'jq.liQiu': 'Lập Thu',
    'jq.chuShu': 'Xử Thử',
    'jq.baiLu': 'Bạch Lộ',
    'jq.qiuFen': 'Thu Phân',
    'jq.hanLu': 'Hàn Lộ',
    'jq.shuangJiang': 'Sương Giáng',
    'jq.liDong': 'Lập Đông',
    'jq.xiaoXue': 'Tiểu Tuyết',
    'jq.daXue': 'Đại Tuyết',
};

export const HeavenlyStems = {
    'tg.jia': 'Giáp',
    'tg.yi': 'Ất',
    'tg.bing': 'Bính',
    'tg.ding': 'Đinh',
    'tg.wu': 'Mậu',
    'tg.ji': 'Kỷ',
    'tg.geng': 'Canh',
    'tg.xin': 'Tân',
    'tg.ren': 'Nhâm',
    'tg.gui': 'Quý',
};

export const EarthlyBranches = {
    'dz.zi': 'Tý',
    'dz.chou': 'Sửu',
    'dz.yin': 'Dần',
    'dz.mao': 'Mão',
    'dz.chen': 'Thìn',
    'dz.si': 'Tỵ',
    'dz.wu': 'Ngọ',
    'dz.wei': 'Mùi',
    'dz.shen': 'Thân',
    'dz.you': 'Dậu',
    'dz.xu': 'Tuất',
    'dz.hai': 'Hợi',
};

export const Zodiac = {
    'sx.shu': 'Chuột',
    'sx.niu': 'Trâu',
    'sx.hu': 'Hổ',
    'sx.tu': 'Mèo', // VN uses Cat
    'sx.long': 'Rồng',
    'sx.she': 'Rắn',
    'sx.ma': 'Ngựa',
    'sx.yang': 'Dê',
    'sx.hou': 'Khỉ',
    'sx.ji': 'Gà',
    'sx.gou': 'Chó',
    'sx.zhu': 'Lợn',
};

export const YiJi = {
    'yj.jiSi': 'Cúng tế',
    'yj.qiFu': 'Cầu phúc',
    'yj.qiuSi': 'Cầu tự',
    'yj.kaiGuang': 'Khai quang',
    'yj.suHui': 'Vẽ trần',
    'yj.qiJiao': 'Làm lẽ',
    'yj.zhaiJiao': 'Làm chay',
    'yj.muYu': 'Tắm gội',
    'yj.chouShen': 'Tạ ơn thần',
    'yj.zaoMiao': 'Xây miếu',
    'yj.siZhao': 'Tế táo',
    'yj.fenXiang': 'Thắp hương',
    'yj.xieTu': 'Tạ thổ',
    'yj.chuHuo': 'Xuất lửa',
    'yj.diaoKe': 'Điêu khắc',
    'yj.jiaQu': 'Cưới hỏi',
    'yj.DingHun': 'Đính hôn',
    'yj.naCai': 'Nạp tài',
    'yj.wenMing': 'Hỏi danh',
    'yj.naXu': 'Nạp rể',
    'yj.guiNing': 'Về nhà gái',
    'yj.anChuang': 'An sàng',
    'yj.heZhang': 'Lập khế ước',
    'yj.guanJi': 'Lễ trưởng thành',
    'yj.dingMeng': 'Đính ước',
    'yj.jinRenKou': 'Nhận người',
    'yj.caiYi': 'May áo',
    'yj.wanMian': 'Vẽ mặt',
    'yj.kaiRong': 'Cắt tóc',
    'yj.xiuFen': 'Tu sửa mộ',
    'yj.qiZuan': 'Khai huyệt',
    'yj.poTu': 'Động thổ',
    'yj.anZang': 'An táng',
    'yj.liBei': 'Lập bia',
    'yj.chengFu': 'Thành phục',
    'yj.chuFu': 'Trừ phục',
    'yj.kaiShengFen': 'Khai sinh phần',
    'yj.heShouMu': 'Làm quan tài',
    'yj.ruLian': 'Nhập liệm',
    'yj.yiJiu': 'Di cữu',
    'yj.puDu': 'Phổ độ',
    'yj.ruZhai': 'Nhập trạch',
    'yj.anXiang': 'An hương',
    'yj.anMen': 'Lắp cửa',
    'yj.xiuZao': 'Tu tạo',
    'yj.qiJi': 'Đổ móng',
    'yj.dongTu': 'Động thổ',
    'yj.shangLiang': 'Thượng lương',
    'yj.shuZhu': 'Dựng cột',
    'yj.kaiJing': 'Khai giếng',
    'yj.zuoBei': 'Đắp đê',
    'yj.chaiXie': 'Dỡ nhà',
    'yj.poWu': 'Phá nhà',
    'yj.huaiYuan': 'Phá tường',
    'yj.buYuan': 'Vá tường',
    'yj.faMuZuoLiang': 'Chặt gỗ làm dầm',
    'yj.zuoZhao': 'Làm bếp',
    'yj.jieChu': 'Giải trừ',
    'yj.kaiZhuYan': 'Mở cột',
    'yj.chuanPing': 'Đóng màn',
    'yj.gaiWuHeJi': 'Lợp mái',
    'yj.kaiCe': 'Đào nhà xí',
    'yj.zaoCang': 'Xây kho',
    'yj.saiXue': 'Lấp hang',
    'yj.pingZhi': 'San đường',
    'yj.zaoQiao': 'Xây cầu',
    'yj.zuoCe': 'Làm nhà xí',
    'yj.zhuDi': 'Đắp nền',
    'yj.kaiChi': 'Đào ao',
    'yj.faMu': 'Chặt cây',
    'yj.kaiQu': 'Khai mương',
    'yj.jueJing': 'Đào giếng',
    'yj.saoShe': 'Quét nhà',
    'yj.fangShui': 'Tháo nước',
    'yj.zaoWu': 'Xây nhà',
    'yj.heJi': 'Hợp tích',
    'yj.zaoChuChou': 'Chuồng gia súc',
    'yj.xiuMen': 'Sửa cửa',
    'yj.dingSang': 'Định táng',
    'yj.zuoLiang': 'Làm dầm',
    'yj.xiuShi': 'Tu thất',
    'yj.jiaMa': 'Giá mã',
    'yj.kaiShi': 'Khai trương',
    'yj.guaBian': 'Treo biển',
    'yj.naChai': 'Nạp sính lễ',
    'yj.qiuCai': 'Cầu tài',
    'yj.kaiCang': 'Mở kho',
    'yj.maiChe': 'Mua xe',
    'yj.zhiChan': 'Mua nhà đất',
    'yj.guYong': 'Thuê người',
    'yj.chuHuoCai': 'Xuất hàng',
    'yj.anJiXie': 'Lắp máy',
    'yj.zaoCheQi': 'Chế xe',
    'yj.jingLuo': 'Kinh lạc',
    'yj.yunNiang': 'Ủ men',
    'yj.zuoRan': 'Nhuộm',
    'yj.guZhu': 'Đúc',
    'yj.zaoChuan': 'Đóng thuyền',
    'yj.geMi': 'Lấy mật',
    'yj.zaiZhong': 'Trồng trọt',
    'yj.quYu': 'Đánh cá',
    'yj.jieWang': 'Kết lưới',
    'yj.muYang': 'Chăn nuôi',
    'yj.anDuiWei': 'Xây cối',
    'yj.xiYi': 'Học nghề',
    'yj.ruXue': 'Nhập học',
    'yj.liFa': 'Cắt tóc',
    'yj.tanBing': 'Thăm bệnh',
    'yj.jianGui': 'Gặp người n.',
    'yj.chengChuan': 'Đi thuyền',
    'yj.duShui': 'Qua sông',
    'yj.zhenJiu': 'Châm cứu',
    'yj.chuXing': 'Xuất hành',
    'yj.yiXi': 'Di cư',
    'yj.fenJu': 'Phân cư',
    'yj.TiTou': 'Cạo đầu',
    'yj.zhengShou': 'Chỉnh thủ',
    'yj.naChu': 'Nạp súc',
    'yj.buZhuo': 'Săn bắt',
    'yj.tianLie': 'Đi săn',
    'yj.jiaoNiuMa': 'Huấn luyện',
    'yj.huiQinYou': 'Họp mặt',
    'yj.fuRen': 'Nhậm chức',
    'yj.qiuYi': 'Cầu y',
    'yj.zhiBing': 'Trị bệnh',
    'yj.ciSong': 'Kiện tụng',
    'yj.qiJiDongTu': 'Động thổ',
    'yj.poWuHuaiYuan': 'Phá dỡ',
    'yj.gaiWu': 'Lợp nhà',
    'yj.zaoCangKu': 'Xây kho',
    'yj.liQuanJiaoYi': 'Giao dịch',
    'yj.jiaoYi': 'Giao dịch',
    'yj.liQuan': 'Lập khoán',
    'yj.anJi': 'An cơ',
    'yj.huiYou': 'Gặp bạn',
    'yj.qiuYiLiaoBing': 'Chữa bệnh',
    'yj.zhuShi': 'Mọi việc',
    'yj.yuShi': 'Các việc khác',
    'yj.xingSang': 'Phát tang',
    'yj.duanYi': 'Đoạn nghi',
    'yj.guiXiu': 'Quy tu',
};

export const LunarVN = {
    ...SolarTerms,
    ...HeavenlyStems,
    ...EarthlyBranches,
    ...Zodiac,
    ...YiJi,
    'di.wang': 'Đế Vượng',
    'di.shuai': 'Suy',
    'di.bing': 'Bệnh',
    'di.si': 'Tử',
    'di.mu': 'Mộ',
    'di.jue': 'Tuyệt',
    'di.tai': 'Thai',
    'di.yang': 'Dưỡng',
    'di.changSheng': 'Trường Sinh',
    'di.muYu': 'Mộc Dục',
    'di.guanDai': 'Quan Đới',
    'di.linGuan': 'Lâm Quan',
    'ts.qingLong': 'Thanh Long',
    'ts.mingTang': 'Minh Đường',
    'ts.tianXing': 'Thiên Hình',
    'ts.zhuQue': 'Chu Tước',
    'ts.jinGui': 'Kim Quỹ',
    'ts.tianDe': 'Thiên Đức',
    'ts.baiHu': 'Bạch Hổ',
    'ts.yuTang': 'Ngọc Đường',
    'ts.tianLao': 'Thiên Lao',
    'ts.xuanWu': 'Huyền Vũ',
    'ts.siMing': 'Tư Mệnh',
    'ts.gouChen': 'Câu Trần',
};
